/**
 * Ingested from /workspace/sex-dev-oral-sex-act-dares.md (78 one-liners).
 * Mapped: mild→romantic/spicy, medium→spicy/fire, spicy→fire/hard.
 */
import type { ChallengeCard, ForfeitCard, ShopItem } from '../types'

export const DARE_FORFEITS: ForfeitCard[] = [
  // Oral teasing / warm-up
  { id: 'dp-f01', title: 'Thigh Trail Stop', description: 'Kiss their inner thighs slowly, working upward — stop just short.', intensities: ['romantic', 'spicy', 'fire', 'hard'], media: 'touch' },
  { id: 'dp-f02', title: 'Stomach Lips Only', description: 'Kiss every inch of their stomach with only your lips — no hands.', intensities: ['romantic', 'spicy', 'fire', 'hard'], media: 'touch' },
  { id: 'dp-f03', title: 'Collarbone to Navel', description: 'Trail your tongue from collarbone to navel once, very slowly.', intensities: ['romantic', 'spicy', 'fire', 'hard'], media: 'touch' },
  { id: 'dp-f04', title: 'Waistband Only', description: 'Kiss along the waistband — do not go lower yet.', intensities: ['romantic', 'spicy', 'fire', 'hard'], media: 'touch' },
  { id: 'dp-f05', title: 'Tongue Dirty Word', description: 'Spell a dirty word on their skin using only your tongue.', intensities: ['spicy', 'fire', 'hard'], media: 'touch' },
  { id: 'dp-f06', title: 'Mouth Undress One', description: 'Remove one piece of their clothing using only your mouth.', intensities: ['spicy', 'fire', 'hard'], media: 'touch' },
  { id: 'dp-f07', title: 'Teeth Underwear', description: 'Take off their underwear with your teeth.', intensities: ['fire', 'hard'], media: 'touch' },
  { id: 'dp-f08', title: 'Stop Before Good', description: 'Kiss your way down their body and stop just before the good part.', intensities: ['spicy', 'fire', 'hard'], media: 'touch' },
  { id: 'dp-f09', title: 'No-Hands Unzip', description: 'Unzip / unbutton them without using your hands.', intensities: ['spicy', 'fire', 'hard'], media: 'touch' },
  { id: 'dp-f10', title: 'Mouth Above Waist', description: 'Explore them for two minutes using only your mouth — stay above the waist first.', intensities: ['romantic', 'spicy', 'fire', 'hard'], media: 'touch' },

  // Oral giving
  { id: 'dp-f11', title: 'Hands Behind Oral', description: 'Give oral for two minutes while they keep their hands behind their back.', intensities: ['fire', 'hard'], media: 'touch' },
  { id: 'dp-f12', title: 'Mouth Finish', description: 'Finish your partner using only your mouth.', intensities: ['fire', 'hard'], media: 'touch' },
  { id: 'dp-f13', title: 'Mouth Only Moans', description: 'Use your mouth only — make them moan; no hands allowed.', intensities: ['fire', 'hard'], media: 'touch' },
  { id: 'dp-f14', title: 'Soft Scarf Oral', description: 'Tie (soft scarf) their hands and please them orally. Agree release + safeword first.', intensities: ['hard'], media: 'touch' },
  { id: 'dp-f15', title: 'Hum & Guess', description: 'While going down, hum a song and make them guess what it is.', intensities: ['spicy', 'fire', 'hard'], media: 'touch' },
  { id: 'dp-f16', title: 'Give-Only Oral', description: 'Give oral with no expectation of reciprocation this round — focus only on them.', intensities: ['fire', 'hard'], media: 'touch' },
  { id: 'dp-f17', title: 'Bed Edge Kneel', description: 'Partner sits on the edge of the bed; kneel and take your time with your mouth.', intensities: ['fire', 'hard'], media: 'touch' },
  { id: 'dp-f18', title: 'Hands Above Head', description: 'Hold their hands above their head while you take them with your mouth.', intensities: ['fire', 'hard'], media: 'touch' },
  { id: 'dp-f19', title: 'Edge Twice Then Finish', description: 'Bring them to the edge twice with your mouth before letting them finish however they want.', intensities: ['fire', 'hard'], media: 'touch' },
  { id: 'dp-f20', title: 'Narrated Oral', description: 'Use your mouth for two minutes while they narrate what they feel.', intensities: ['fire', 'hard'], media: 'touch' },
  { id: 'dp-f21', title: 'Guided Hair Oral', description: 'Use your mouth while they keep one hand in your hair, guiding.', intensities: ['fire', 'hard'], media: 'touch' },
  { id: 'dp-f22', title: 'Use My Mouth', description: 'Let them use your mouth however they want for two minutes (within agreed limits).', intensities: ['hard'], media: 'touch' },
  { id: 'dp-f23', title: 'Pillow Hip Oral', description: 'Partner on their stomach, pillow under hips — slow oral for two minutes at your tempo.', intensities: ['fire', 'hard'], media: 'touch' },
  { id: 'dp-f24', title: 'Mouth/Hand Switch', description: 'Alternate mouth and hand every 30 seconds until they ask you to stop switching.', intensities: ['fire', 'hard'], media: 'touch' },
  { id: 'dp-f25', title: 'Edge No Climax', description: 'Edge them with mouth or hand for two minutes — no climax yet.', intensities: ['fire', 'hard'], media: 'touch' },
  { id: 'dp-f26', title: 'Three Almosts', description: 'Come as close as you can three times with your mouth without finishing — then let them decide.', intensities: ['hard'], media: 'touch' },
  { id: 'dp-f27', title: 'Ice & Warm Mouth', description: 'Blindfolded partner: alternate cold ice and warm mouth for 90 seconds anywhere below the waist.', intensities: ['fire', 'hard'], media: 'touch' },
  { id: 'dp-f28', title: '69 Then Switch', description: 'Sixty-nine for two minutes, then stop and switch to something else entirely.', intensities: ['fire', 'hard'], media: 'touch' },
  { id: 'dp-f32', title: 'Ask Then Taste', description: 'Taste them somewhere extra sensitive — ask where first.', intensities: ['spicy', 'fire', 'hard'], media: 'touch' },

  // Hands
  { id: 'dp-f56', title: 'Hands Until Beg', description: 'Pleasure them using only your hands until they beg to finish.', intensities: ['fire', 'hard'], media: 'touch' },
  { id: 'dp-f59', title: 'Stop On Their Count', description: 'Build them up, then stop — on their count, not yours (edge).', intensities: ['fire', 'hard'], media: 'touch' },
  { id: 'dp-f64', title: 'Hand + Kiss Lock', description: 'Finish them with your hand while kissing them — no break in the kiss.', intensities: ['fire', 'hard'], media: 'touch' },
  { id: 'dp-f76', title: 'Make Them Beg', description: 'Make them beg for it before they get anything.', intensities: ['fire', 'hard'], media: 'touch' },
]

export const DARE_SHOP: ShopItem[] = [
  {
    id: 'dp-s11',
    title: 'Hands-Behind Oral',
    description: 'Give oral for two minutes while they keep their hands behind their back.',
    price: 30,
    category: 'oral',
    rarity: 'filthy',
    intensities: ['fire', 'hard'],
    unlockRound: 4,
  },
  {
    id: 'dp-s12',
    title: 'Mouth Finish',
    description: 'Finish your partner using only your mouth.',
    price: 40,
    category: 'oral',
    rarity: 'filthy',
    intensities: ['fire', 'hard'],
    unlockRound: 5,
  },
  {
    id: 'dp-s14',
    title: 'Soft Restraint Oral',
    description: 'Tie (soft scarf) their hands and please them orally. Safeword + release agreed first.',
    price: 48,
    category: 'oral',
    rarity: 'depraved',
    intensities: ['hard'],
    unlockRound: 6,
  },
  {
    id: 'dp-s19',
    title: 'Double Edge Oral',
    description: 'Bring them to the edge twice with your mouth before letting them finish however they want.',
    price: 42,
    category: 'oral',
    rarity: 'filthy',
    intensities: ['fire', 'hard'],
    unlockRound: 5,
  },
  {
    id: 'dp-s22',
    title: 'Use Their Mouth',
    description: 'Use their mouth however you want for two minutes (within agreed limits). Safeword on.',
    price: 50,
    category: 'oral',
    rarity: 'depraved',
    intensities: ['hard'],
    unlockRound: 7,
  },
  {
    id: 'dp-s28',
    title: '69 Twist',
    description: 'Sixty-nine for two minutes, then stop and switch to something else entirely.',
    price: 36,
    category: 'oral',
    rarity: 'filthy',
    intensities: ['spicy', 'fire', 'hard'],
    unlockRound: 5,
  },
  {
    id: 'dp-s30',
    title: 'Oral-Only Round',
    description: 'No penetration until one of you taps out or the timer ends (5 min). Mouth only.',
    price: 38,
    category: 'oral',
    rarity: 'filthy',
    intensities: ['fire', 'hard'],
    unlockRound: 6,
  },
  {
    id: 'dp-s33',
    title: 'Brand New Position',
    description: 'Try a new position you’ve never done before — right now.',
    price: 32,
    category: 'penetration',
    rarity: 'filthy',
    intensities: ['spicy', 'fire', 'hard'],
    unlockRound: 6,
  },
  {
    id: 'dp-s35',
    title: 'Mirror Sex',
    description: 'Have sex in front of a mirror and watch the entire time.',
    price: 44,
    category: 'penetration',
    rarity: 'filthy',
    intensities: ['fire', 'hard'],
    unlockRound: 7,
  },
  {
    id: 'dp-s37',
    title: 'Eye Contact Lock',
    description: 'Have sex while keeping intense eye contact the entire time — no looking away.',
    price: 40,
    category: 'penetration',
    rarity: 'filthy',
    intensities: ['fire', 'hard'],
    unlockRound: 7,
  },
  {
    id: 'dp-s41',
    title: 'Half-Dressed Wall',
    description: 'Take them slowly against the nearest wall, both still half-dressed.',
    price: 45,
    category: 'penetration',
    rarity: 'filthy',
    intensities: ['fire', 'hard'],
    unlockRound: 7,
  },
  {
    id: 'dp-s46',
    title: 'Five Minute Slow',
    description: 'Slow, deep, and unhurried for five minutes — no changing pace no matter what they ask.',
    price: 42,
    category: 'penetration',
    rarity: 'filthy',
    intensities: ['spicy', 'fire', 'hard'],
    unlockRound: 6,
  },
  {
    id: 'dp-s50',
    title: 'Consent Rough',
    description: 'Rough play only with clear consent + safeword: hair pull / spank / intense eye contact as agreed.',
    price: 55,
    category: 'domination',
    rarity: 'depraved',
    intensities: ['hard'],
    unlockRound: 8,
  },
  {
    id: 'dp-s51',
    title: 'Position Roulette',
    description: '30 seconds each — missionary → on top → from behind → side → standing — then repeat.',
    price: 48,
    category: 'penetration',
    rarity: 'filthy',
    intensities: ['fire', 'hard'],
    unlockRound: 8,
  },
  {
    id: 'dp-s61',
    title: 'Introduce a Toy',
    description: 'Use a toy, or introduce one for the first time (mutually agreed).',
    price: 34,
    category: 'toys',
    rarity: 'filthy',
    intensities: ['spicy', 'fire', 'hard'],
    unlockRound: 4,
  },
  {
    id: 'dp-s62',
    title: 'Toy + Instructions',
    description: 'Use a toy on yourself while they watch and give instructions.',
    price: 36,
    category: 'toys',
    rarity: 'filthy',
    intensities: ['fire', 'hard'],
    unlockRound: 5,
  },
  {
    id: 'dp-s71',
    title: 'Ten Minutes Control',
    description: 'Let your partner take full control for the next 10 minutes (within limits).',
    price: 35,
    category: 'domination',
    rarity: 'filthy',
    intensities: ['spicy', 'fire', 'hard'],
    unlockRound: 4,
  },
  {
    id: 'dp-s73',
    title: 'Fifteen Minute Commands',
    description: 'Let them command you for the next 15 minutes. Safeword on.',
    price: 45,
    category: 'domination',
    rarity: 'depraved',
    intensities: ['fire', 'hard'],
    unlockRound: 6,
  },
]

export const DARE_CHALLENGES: ChallengeCard[] = [
  // Mild → romantic/spicy, rounds 1-3 apart friendly where possible
  { id: 'dp-c01', title: 'Thigh Tease Text', description: 'If apart: voice-note describing kissing their inner thighs and stopping short. If together: do it.', roundMin: 1, roundMax: 4, intensities: ['romantic', 'spicy'], media: 'audio' },
  { id: 'dp-c02', title: 'Stomach Map', description: 'Kiss every inch of their stomach with only your lips — no hands. (Photo proof if apart.)', roundMin: 1, roundMax: 5, intensities: ['romantic', 'spicy', 'fire'], media: 'touch' },
  { id: 'dp-c05', title: 'Tongue Word', description: 'Spell a dirty word on their skin using only your tongue.', roundMin: 2, roundMax: 6, intensities: ['spicy', 'fire'], media: 'touch' },
  { id: 'dp-c10', title: 'Above-Waist Mouth', description: 'Explore with only your mouth for two minutes — above the waist first.', roundMin: 2, roundMax: 5, intensities: ['romantic', 'spicy', 'fire'], media: 'touch' },
  { id: 'dp-c29', title: 'Side-by-Side Song', description: 'Try side-by-side mutual oral for the length of one song.', roundMin: 7, roundMax: 10, intensities: ['fire', 'hard'], media: 'touch' },
  { id: 'dp-c30', title: 'Oral-Only Timer', description: 'Oral-only round: no penetration until one of you taps out or 5 minutes end.', roundMin: 7, roundMax: 10, intensities: ['fire', 'hard'], media: 'touch' },
  { id: 'dp-c33', title: 'Never-Tried Position', description: 'Try a new position you’ve never done before — right now.', roundMin: 7, roundMax: 10, intensities: ['spicy', 'fire', 'hard'], media: 'touch' },
  { id: 'dp-c34', title: 'New Room (Home)', description: 'Have sex in a room you’ve never used before (private home only).', roundMin: 8, roundMax: 10, intensities: ['fire', 'hard'], media: 'touch' },
  { id: 'dp-c35', title: 'Mirror Watch', description: 'Have sex in front of a mirror and watch the entire time.', roundMin: 7, roundMax: 10, intensities: ['fire', 'hard'], media: 'touch' },
  { id: 'dp-c36', title: 'Ride Eye Minute', description: 'Ride them without breaking eye contact for one full minute.', roundMin: 7, roundMax: 10, intensities: ['spicy', 'fire', 'hard'], media: 'touch' },
  { id: 'dp-c40', title: 'Slow Face Down', description: 'Hold them face down, hips raised, and enter as slowly as you can manage.', roundMin: 8, roundMax: 10, intensities: ['hard'], media: 'touch' },
  { id: 'dp-c45', title: 'No Hands Sex', description: 'Have sex without using your hands at all.', roundMin: 7, roundMax: 10, intensities: ['fire', 'hard'], media: 'touch' },
  { id: 'dp-c48', title: 'First Time Replay', description: 'Recreate the first time you slept together — set the scene, then start.', roundMin: 6, roundMax: 10, intensities: ['romantic', 'spicy', 'fire'], media: 'touch' },
  { id: 'dp-c49', title: 'Complete Darkness', description: 'Intimacy in complete darkness this round.', roundMin: 4, roundMax: 8, intensities: ['romantic', 'spicy', 'fire'], media: 'touch' },
  { id: 'dp-c51', title: 'Position Roulette', description: '30s each: missionary → on top → from behind → side → standing — repeat.', roundMin: 8, roundMax: 10, intensities: ['fire', 'hard'], media: 'touch' },
  { id: 'dp-c53', title: 'Full Body Five', description: 'Full-body massage — don’t skip anywhere — for five minutes.', roundMin: 3, roundMax: 7, intensities: ['romantic', 'spicy'], media: 'touch' },
  { id: 'dp-c57', title: 'Guide Their Hand', description: 'Show them your favourite way to be touched — guide their hand.', roundMin: 2, roundMax: 6, intensities: ['romantic', 'spicy', 'fire'], media: 'touch' },
  { id: 'dp-c65', title: 'Watch Each Other', description: 'Mutual self-pleasure while watching each other for two minutes.', roundMin: 4, roundMax: 8, intensities: ['spicy', 'fire', 'hard'], media: 'touch' },
  { id: 'dp-c68', title: 'Blindfold Tease', description: 'Blindfold them and tease with feather / silk / breath for three minutes.', roundMin: 3, roundMax: 7, intensities: ['romantic', 'spicy', 'fire'], media: 'touch' },
  { id: 'dp-c69', title: '30-Min Foreplay', description: 'Extended foreplay only — minimum 30 minutes before any penetration.', roundMin: 5, roundMax: 10, intensities: ['romantic', 'spicy', 'fire'], media: 'touch' },
  { id: 'dp-c70', title: 'Narrate Everything', description: 'Narrate what you’re doing out loud as you do it — don’t stop talking.', roundMin: 4, roundMax: 9, intensities: ['spicy', 'fire', 'hard'], media: 'audio' },
  { id: 'dp-c72', title: 'Zero Decisions', description: 'Give up every decision for ten minutes — they choose everything (within limits).', roundMin: 5, roundMax: 10, intensities: ['fire', 'hard'], media: 'touch' },
  { id: 'dp-c75', title: 'Halfway Switch', description: 'Take turns being completely in charge — switch at the halfway point.', roundMin: 4, roundMax: 9, intensities: ['spicy', 'fire', 'hard'], media: 'touch' },
  { id: 'dp-c77', title: 'Say It Plain', description: 'Tell them exactly what you want, out loud, no hints — then they do it.', roundMin: 3, roundMax: 8, intensities: ['romantic', 'spicy', 'fire', 'hard'], media: 'audio' },
  { id: 'dp-c78', title: 'Role Swap Night', description: 'Swap your usual roles tonight — whoever usually leads, follows.', roundMin: 4, roundMax: 10, intensities: ['romantic', 'spicy', 'fire', 'hard'], media: 'touch' },
]
