import type { ShopItem } from '../types'
import { DARE_SHOP } from './darePack'

const BASE_SHOP: ShopItem[] = [
  // —— TEASE ——
  {
    id: 'tease-whisper',
    title: 'Filthy Whisper',
    description: 'Lean in and whisper exactly what you want to do to them for 30 seconds. No touching — words only.',
    price: 8,
    category: 'tease',
    rarity: 'tease',
    intensities: ['romantic', 'spicy', 'fire', 'hard'],
    unlockRound: 1,
  },
  {
    id: 'tease-strip-slow',
    title: 'Slow Strip Tease',
    description: 'Remove one piece of clothing as slowly and seductively as you can while they watch, hands off.',
    price: 12,
    category: 'tease',
    rarity: 'tease',
    intensities: ['romantic', 'spicy', 'fire', 'hard'],
    unlockRound: 1,
  },
  {
    id: 'tease-kiss-everywhere',
    title: 'Kiss Trail',
    description: 'Kiss a slow trail from their neck down to their thighs — stop just short of where they want you.',
    price: 15,
    category: 'tease',
    rarity: 'tease',
    intensities: ['romantic', 'spicy', 'fire', 'hard'],
    unlockRound: 2,
  },
  {
    id: 'tease-edge-talk',
    title: 'Edging Dirty Talk',
    description: 'Describe in detail how you\'d edge them for an hour. Keep going until they beg you to stop talking.',
    price: 18,
    category: 'tease',
    rarity: 'filthy',
    intensities: ['spicy', 'fire', 'hard'],
    unlockRound: 3,
  },
  {
    id: 'tease-mirror',
    title: 'Mirror Show',
    description: 'Stand in front of them (or a mirror) and touch yourself for 60 seconds while locking eyes.',
    price: 22,
    category: 'tease',
    rarity: 'filthy',
    intensities: ['spicy', 'fire', 'hard'],
    unlockRound: 4,
  },
  {
    id: 'tease-deny',
    title: 'Denial Game',
    description: 'Get them desperately turned on for 2 minutes, then stop cold. No orgasm. Leave them aching.',
    price: 25,
    category: 'tease',
    rarity: 'filthy',
    intensities: ['fire', 'hard'],
    unlockRound: 5,
  },

  // —— ORAL ——
  {
    id: 'oral-kiss-down',
    title: 'Mouth Warmup',
    description: 'Use only your mouth on their chest, stomach, and inner thighs for 2 minutes. No further — yet.',
    price: 16,
    category: 'oral',
    rarity: 'tease',
    intensities: ['romantic', 'spicy', 'fire', 'hard'],
    unlockRound: 2,
  },
  {
    id: 'oral-classic',
    title: 'Go Down',
    description: 'Give them oral sex for at least 3 minutes. Focus on making them moan — no rushing to finish.',
    price: 28,
    category: 'oral',
    rarity: 'filthy',
    intensities: ['spicy', 'fire', 'hard'],
    unlockRound: 3,
  },
  {
    id: 'oral-69',
    title: '69 Lock',
    description: 'Get into 69. Neither of you stops until the buyer says so (max 5 minutes). Hands welcome.',
    price: 35,
    category: 'oral',
    rarity: 'filthy',
    intensities: ['spicy', 'fire', 'hard'],
    unlockRound: 5,
  },
  {
    id: 'oral-worship',
    title: 'Cock / Pussy Worship',
    description: 'Spend 4 minutes worshipping them with your mouth like they\'re the only thing that exists. Praise them out loud.',
    price: 32,
    category: 'oral',
    rarity: 'filthy',
    intensities: ['fire', 'hard'],
    unlockRound: 4,
  },
  {
    id: 'oral-deepthroat',
    title: 'Deep Throat Challenge',
    description: 'Take them as deep as you safely can. Hold for a count of 5, then again. Spit and mess encouraged. Safeword always on.',
    price: 45,
    category: 'oral',
    rarity: 'depraved',
    intensities: ['fire', 'hard'],
    unlockRound: 6,
  },
  {
    id: 'oral-throatpie-fantasy',
    title: 'Throatpie Fantasy',
    description: 'Buyer narrates a filthy throatpie fantasy while the performer deep-throats / goes hard with their mouth. Cum talk mandatory. Finish however you both want.',
    price: 55,
    category: 'oral',
    rarity: 'depraved',
    intensities: ['hard'],
    unlockRound: 7,
  },
  {
    id: 'oral-spit-play',
    title: 'Spit & Sloppy',
    description: 'Make it filthy: spit, drool, eye contact, messy oral for 3 minutes. No polite licking — get wrecked.',
    price: 42,
    category: 'oral',
    rarity: 'depraved',
    intensities: ['hard'],
    unlockRound: 6,
  },

  // —— HAND / TOUCH ——
  {
    id: 'hand-stroke',
    title: 'Hand Job Deluxe',
    description: 'Give them a slow, teasing handjob (or fingering) for 3 minutes. Vary speed. Ask what feels best.',
    price: 20,
    category: 'tease',
    rarity: 'tease',
    intensities: ['romantic', 'spicy', 'fire', 'hard'],
    unlockRound: 2,
  },
  {
    id: 'hand-edge',
    title: 'Edge Them Twice',
    description: 'Bring them to the edge twice with your hand. Stop both times. Third time — they get to finish.',
    price: 30,
    category: 'tease',
    rarity: 'filthy',
    intensities: ['spicy', 'fire', 'hard'],
    unlockRound: 4,
  },

  // —— PENETRATION ——
  {
    id: 'pen-grind',
    title: 'Grind Only',
    description: 'Clothes off (or aside). Grind against each other for 2 minutes — no penetration. Make them beg.',
    price: 24,
    category: 'penetration',
    rarity: 'tease',
    intensities: ['spicy', 'fire', 'hard'],
    unlockRound: 4,
  },
  {
    id: 'pen-slow',
    title: 'Slow Fuck',
    description: 'Have sex as slowly as humanly possible for 4 minutes. Deep strokes. Eye contact. No pounding yet.',
    price: 40,
    category: 'penetration',
    rarity: 'filthy',
    intensities: ['spicy', 'fire', 'hard'],
    unlockRound: 6,
  },
  {
    id: 'pen-buyer-position',
    title: 'Buyer\'s Position',
    description: 'Buyer chooses the position. Fuck for at least 5 minutes. Performer follows buyer\'s pace instructions.',
    price: 48,
    category: 'penetration',
    rarity: 'filthy',
    intensities: ['fire', 'hard'],
    unlockRound: 7,
  },
  {
    id: 'pen-rough',
    title: 'Rough Consensual Pound',
    description: 'Hard, rough, enthusiastic fucking — hair pulling, spanking, dirty talk. Check in first. Safeword on. 5+ minutes of heat.',
    price: 60,
    category: 'penetration',
    rarity: 'depraved',
    intensities: ['hard'],
    unlockRound: 8,
  },
  {
    id: 'pen-creampie-talk',
    title: 'Fill Me Fantasy',
    description: 'During sex, the performer begs filthy creampie / fill-me language the whole time. Finish wherever you both agree.',
    price: 50,
    category: 'penetration',
    rarity: 'depraved',
    intensities: ['fire', 'hard'],
    unlockRound: 7,
  },

  // —— ANAL ——
  {
    id: 'anal-tease',
    title: 'Anal Tease',
    description: 'Lube up. Tease their ass with a fingertip / tongue for 2 minutes. No full penetration unless they ask.',
    price: 35,
    category: 'anal',
    rarity: 'filthy',
    intensities: ['fire', 'hard'],
    unlockRound: 5,
  },
  {
    id: 'anal-finger',
    title: 'Finger Fuck Ass',
    description: 'With plenty of lube, finger their ass while doing something else they love (oral, stroking, kissing). 3 minutes.',
    price: 45,
    category: 'anal',
    rarity: 'depraved',
    intensities: ['fire', 'hard'],
    unlockRound: 6,
  },
  {
    id: 'anal-play',
    title: 'Full Anal Play',
    description: 'Anal sex or toy play — go slow, lots of lube, constant check-ins. Buyer sets the pace. Stop means stop.',
    price: 70,
    category: 'anal',
    rarity: 'depraved',
    intensities: ['hard'],
    unlockRound: 8,
  },
  {
    id: 'anal-rim',
    title: 'Rimming Service',
    description: 'Eat their ass like you mean it for at least 3 minutes. Hands free to stroke / finger elsewhere.',
    price: 40,
    category: 'anal',
    rarity: 'depraved',
    intensities: ['hard'],
    unlockRound: 6,
  },

  // —— TOYS ——
  {
    id: 'toy-vibe',
    title: 'Vibrator Control',
    description: 'Buyer controls the vibe / toy on the performer for 3 minutes. Performer keeps hands to themselves.',
    price: 28,
    category: 'toys',
    rarity: 'filthy',
    intensities: ['spicy', 'fire', 'hard'],
    unlockRound: 3,
  },
  {
    id: 'toy-plug',
    title: 'Plug & Play',
    description: 'Insert a plug / toy (with lube). Leave it in during the next mini-game or challenge.',
    price: 38,
    category: 'toys',
    rarity: 'filthy',
    intensities: ['fire', 'hard'],
    unlockRound: 5,
  },
  {
    id: 'toy-forced-orgasm',
    title: 'Forced Orgasm Attempt',
    description: 'Use a toy to try to make them cum in under 3 minutes. They can\'t push your hand away. Safeword still counts.',
    price: 52,
    category: 'toys',
    rarity: 'depraved',
    intensities: ['hard'],
    unlockRound: 7,
  },

  // —— DOMINATION-LIGHT ——
  {
    id: 'dom-kneel',
    title: 'Kneel & Serve',
    description: 'Performer kneels, calls buyer "Sir" or "Mistress" (buyer chooses), and follows 3 simple commands.',
    price: 22,
    category: 'domination',
    rarity: 'tease',
    intensities: ['spicy', 'fire', 'hard'],
    unlockRound: 3,
  },
  {
    id: 'dom-spank',
    title: 'Spanking Round',
    description: '10 firm consensual spanks. Count them out loud. Kiss it better after — or don\'t, buyer\'s call.',
    price: 26,
    category: 'domination',
    rarity: 'filthy',
    intensities: ['spicy', 'fire', 'hard'],
    unlockRound: 4,
  },
  {
    id: 'dom-collar-words',
    title: 'Verbal Collar',
    description: 'For the next 10 minutes of real life, performer asks permission before touching themselves or the buyer.',
    price: 30,
    category: 'domination',
    rarity: 'filthy',
    intensities: ['fire', 'hard'],
    unlockRound: 5,
  },
  {
    id: 'dom-face-sit',
    title: 'Face Sitting',
    description: 'Buyer sits on performer\'s face. Performer\'s only job is tongue and breath. 2+ minutes. Tap out = pause.',
    price: 48,
    category: 'domination',
    rarity: 'depraved',
    intensities: ['fire', 'hard'],
    unlockRound: 7,
  },
  {
    id: 'dom-use-me',
    title: 'Use Me',
    description: 'Performer says "use me" and means it. Buyer has 5 minutes of enthusiastic, consensual free use within agreed limits.',
    price: 65,
    category: 'domination',
    rarity: 'depraved',
    intensities: ['hard'],
    unlockRound: 8,
  },
  {
    id: 'dom-degrade-praise',
    title: 'Filthy Praise',
    description: 'Buyer talks absolute filth while praising them — "good slut", "perfect whore for me", etc. Performer thanks them. Consensual dirty talk only.',
    price: 35,
    category: 'domination',
    rarity: 'depraved',
    intensities: ['hard'],
    unlockRound: 6,
  },
]

export const SHOP_ITEMS: ShopItem[] = [...BASE_SHOP, ...DARE_SHOP]

export function shopFor(intensity: string, round: number): ShopItem[] {
  return SHOP_ITEMS.filter(
    (i) => i.intensities.includes(intensity as never) && i.unlockRound <= round,
  )
}
